- block:

  - name: mc-ncdu | install required packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - mc
      - ncdu

#
#http://ftp.de.debian.org/debian/pool/main/f/firefox/firefox_133.0-1_amd64.deb
#http://deb.debian.org/debian/pool/main/f/firefox/firefox_133.0.orig-l10n-ach.tar.bz2
#
#
