- name: users | create system group
  ansible.builtin.group:
    name: sysusers
    state: present

- name: users | create users
  ansible.builtin.user:
    name: "{{ item.username }}"
    #group: "{{ item }}"
    groups:
       - sysusers
       - vboxsf
#       - sambashare
    shell: /bin/bash
    state: present
    password: "{{ item.password }}"
  loop: "{{ sysusers }}"

- name: users | give sudo access to backend group
  ansible.builtin.blockinfile:
    path: /etc/sudoers
    insertafter: "root    ALL=(ALL)       ALL"
    block: |
      # Gives sudo access to the sysusers group
      %sysusers        ALL=(ALL)       NOPASSWD: ALL

#- name: L O O P   D E B U G   |  nested loop on subelements
#  ansible.builtin.debug:
#    msg: "=====    IDX {{ my_idx }}  ===  {{ item.0.username }}  === {{ item.1 }} "
#  loop: "{{ sysusers | subelements('sshpubkeys') }}"
#  loop_control:
#    index_var: my_idx

- name: users | set authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.0.username }}"
    state: present
    key: "{{ item.1 }}"
  loop: "{{ sysusers | subelements('sshpubkeys') }}"


- name: create subdirs in VBoxShared dir .mozilla
  ansible.builtin.file:
    path: "/media/sf_VBxShCfg/{{ item.username }}/.mozilla"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0755'
    state: directory
  loop: "{{ sysusers }}"
- name: create symlinks to VBoxShared dir
  ansible.builtin.file:
    dest:  "/home/{{ item.username }}/.mozilla"
    src: "/media/sf_VBxShCfg/{{ item.username }}/.mozilla"
    state: link
  loop: "{{ sysusers }}"

- name: create subdirs in VBoxShared dir .config
  ansible.builtin.file:
    path: "/media/sf_VBxShCfg/{{ item.username }}/.config/google-chrome"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0755'
    state: directory
  loop: "{{ sysusers }}"
- name: create symlinks to VBoxShared dir
  ansible.builtin.file:
    dest:  "/home/{{ item.username }}/.config/google-chrome"
    src: "/media/sf_VBxShCfg/{{ item.username }}/.config/google-chrome"
    state: link
  loop: "{{ sysusers }}"

- name: create subdirs in VBoxShared dir .config
  ansible.builtin.file:
    path: "/media/sf_VBxShCfg/{{ item.username }}/.config/discord"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0777'
    state: directory
  loop: "{{ sysusers }}"
- name: create symlinks to VBoxShared dir
  ansible.builtin.file:
    dest: "/home/{{ item.username }}/.config/discord"
    src:  "/media/sf_VBxShCfg/{{ item.username }}/.config/discord"
    state: link
  loop: "{{ sysusers }}"

- name: Install a discord.deb package from the internet
  ansible.builtin.apt:
    deb: https://dl.discordapp.net/apps/linux/0.0.76/discord-0.0.76.deb

#- name: users | create .themes dir
#  ansible.builtin.file:
#    owner: "{{ item.username }}"
#    group: "{{ item.username }}"
#    state: directory
#    mode: '0755'
#    path:  "/home/{{ item.username }}/.themes"
#  loop: "{{ sysusers }}"

#- name: users | add UA2 theme - select it in Window manager -> Style -> Theme -> UA2
#  ansible.builtin.unarchive:
#    src: "files/UA2-xfce-theme.tar.gz"
#    dest: "/home/{{ item.username }}/.themes"
#    #remote_src: yes
#    owner: "{{ item.username }}"
#    group: "{{ item.username }}"
#    mode: '0755'
#  loop: "{{ sysusers }}"



#- name: users | set theme
#  ansible.builtin.lineinfile:
#    path: /home/{{ item }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
#    regexp: '.*<property name="theme" type="string" value=".*"/>'
#    line: '<property name="theme" type="string" value="UA2"/>'
#  loop: "{{ sysusers }}"
